### ISSUE TITLE
Game engine

### ISSUE THREAD

**Issue by vadhub** [GabderHub-Happiness/Sisyphus#1]
Need will choose one of game engine for java
several options: 

1. [PlayN](https://github.com/playn/playn)
2. [FXGL](https://github.com/AlmasB/FXGL)
3. [Mini2Dx](https://github.com/mini2Dx/mini2Dx)
4. [blade](https://github.com/bladecoder/bladecoder-adventure-engine)

**Comment by Good1Cheese** [comment]
Yes, the end is near.
